# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoginscript():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}

  
  def test_loginscript(self):
      self.driver.get("https://corporate-uat.apdbank.com.kh/login")
      self.driver.set_window_size(1520, 970)

      # Enter Username
      self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(3) > .el-input__inner").click()
      time.sleep(1)
      self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(3) > .el-input__inner").send_keys("8888100106")

      # Enter Password
      self.driver.find_element(By.CSS_SELECTOR,
                               ".login-from-item:nth-child(1) .el-form-item__content > .el-input > .el-input__inner").click()
      self.driver.find_element(By.CSS_SELECTOR,
                               ".login-from-item:nth-child(1) .el-form-item__content > .el-input > .el-input__inner").send_keys(
          "Apd1234567!")

      # Submit first stage
      self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2)").click()
      time.sleep(3)
      self.driver.find_element(By.ID, "loginBtn").click()
      time.sleep(2)
      self.driver.find_element(By.CSS_SELECTOR, ".company-list-item:nth-child(1) .company-custEngName").click()
      self.driver.find_element(By.LINK_TEXT, "Confirm").click()
      time.sleep(2)
      self.driver.find_element(By.CSS_SELECTOR,
                               ".login-from-item:nth-child(1) > .otp-items-box .el-input__inner").send_keys("123456")
      self.driver.find_element(By.ID, "submitForm").click()

      #--- AUTO-CHANGE TO HOME ---
      #Wait 5 seconds for the login session to register, then jump to home
      time.sleep(5)
      print("Switching from /login to /home...")
      self.driver.get("https://corporate-uat.apdbank.com.kh/home")

      # Verification
      assert "/home" in self.driver.current_url
      print("Successfully reached the Home Page!")

      self.driver.set_window_size(1520, 970)
      self.driver.find_element(By.CSS_SELECTOR, ".language-select .el-input__inner").click()
      self.driver.find_element(By.CSS_SELECTOR, ".hover > span").click()
      self.driver.find_element(By.CSS_SELECTOR, ".language-select .el-input__inner").click()
      self.driver.find_element(By.CSS_SELECTOR, ".hover > span").click()
      self.driver.find_element(By.CSS_SELECTOR, ".language-select .el-input__inner").click()
      self.driver.find_element(By.CSS_SELECTOR, ".hover > span").click()



  
