# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestViewfdscript():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_viewfdscript(self):
    self.driver.get("https://corporate-uat.apdbank.com.kh/home")
    self.driver.set_window_size(1520, 970)
    self.driver.find_element(By.CSS_SELECTOR, ".el-menu-item:nth-child(11) img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fixed-list-item:nth-child(1) > .list-box").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fixed-list-item:nth-child(2) > .list-box > .content").click()
  
