# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestOpenfdscript():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_openfdscript(self):
    self.driver.get("https://corporate-uat.apdbank.com.kh/home")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.CSS_SELECTOR, ".el-menu-item:nth-child(11) img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".open-fixed-deposit img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fixed-list:nth-child(4) .btn > img").click()
    self.driver.find_element(By.LINK_TEXT, "Select product").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn > img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".account-list-item:nth-child(1) .content").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-slider__runway").click()
    self.driver.find_element(By.CSS_SELECTOR, ".transfer-input-box .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".transfer-input-box .el-input__inner").send_keys("200")
    self.driver.find_element(By.CSS_SELECTOR, ".select-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".custom-checkbox:nth-child(3) .el-checkbox__label").click()
    self.driver.find_element(By.LINK_TEXT, "Confirm").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".terms .el-checkbox__inner").click()
    self.driver.find_element(By.LINK_TEXT, "Confirm").click()
    self.driver.find_element(By.CSS_SELECTOR, ".round").click()
    self.driver.find_element(By.CSS_SELECTOR, ".input-code > .el-input__inner").send_keys("1111")
    self.driver.find_element(By.LINK_TEXT, "Log Out").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn > .small:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(3) > .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(3) > .el-input__inner").send_keys("8888100122")
    self.driver.find_element(By.CSS_SELECTOR, ".login-from-item:nth-child(1) .el-form-item__content > .el-input > .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".login-from-item:nth-child(1) .el-form-item__content > .el-input > .el-input__inner").send_keys("Apd1234567!")
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "loginBtn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2)").click()
    self.driver.find_element(By.ID, "loginBtn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".company-list-item:nth-child(1) .company-custEngName").click()
    self.driver.find_element(By.LINK_TEXT, "Confirm").click()
    self.driver.find_element(By.CSS_SELECTOR, ".login-from-item:nth-child(1) > .otp-items-box .el-input__inner").send_keys("123456")
    self.driver.find_element(By.ID, "submitForm").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-table__row:nth-child(1) > .el-table_2_column_7 > .cell").click()
    self.driver.find_element(By.LINK_TEXT, "Approve").click()
    self.driver.find_element(By.CSS_SELECTOR, ".input-code > .el-input__inner").send_keys("1111")
    self.driver.find_element(By.CSS_SELECTOR, "#close > img").click()
  
