# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDashboardsnapshotscript():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_dashboardsnapshotscript(self):
    self.driver.get("https://corporate-uat.apdbank.com.kh/home")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.CSS_SELECTOR, "img:nth-child(2)").click()
    self.driver.find_element(By.LINK_TEXT, "Snapshot").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > .text:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").send_keys("1200")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Snapshot").click()
  
