# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestStatusoverviewscript():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_statusoverviewscript(self):
    self.driver.get("https://corporate-uat.apdbank.com.kh/home")
    self.driver.set_window_size(1520, 970)
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(5) canvas").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(5) canvas").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(5) canvas").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(2) .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".hover .el-checkbox__label").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(5) canvas").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(5) canvas").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(5) canvas").click()
  
