# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDownloadstatementscript():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_downloadstatementscript(self):
    self.driver.get("https://corporate-uat.apdbank.com.kh/home")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.CSS_SELECTOR, ".el-menu-item:nth-child(2) img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".account-list-item:nth-child(1) > .content").click()
    self.driver.find_element(By.CSS_SELECTOR, ".header > .btn").click()
    self.driver.find_element(By.LINK_TEXT, "Download Account statement").click()
    self.driver.find_element(By.CSS_SELECTOR, ".custom-checkbox:nth-child(2) .el-checkbox__inner").click()
    self.driver.find_element(By.LINK_TEXT, "Confirm").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-switch__label--right > span").click()
    self.driver.find_element(By.LINK_TEXT, "Confirm").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-dialog__close > svg").click()
  
