# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSignupscript():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_signupscript(self):
    self.driver.get("https://corporate-uat.apdbank.com.kh/login")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.CSS_SELECTOR, ".el-switch__label--right > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(3) > .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(3) > .el-input__inner").send_keys("8888100410")
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(2) .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(2) .el-input__inner").send_keys("00005887")
    self.driver.find_element(By.CSS_SELECTOR, ".sign-up-btn").click()
    self.driver.find_element(By.ID, "nextStep").click()
    self.driver.find_element(By.CSS_SELECTOR, ".otp-input .el-input__inner").send_keys("123456")
    self.driver.find_element(By.ID, "nextStep").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(6) .el-input__inner").send_keys("Apd1234567!")
    element = self.driver.find_element(By.CSS_SELECTOR, ".sign-up-btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "nextStep")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".sign-up-btn").click()
    self.driver.find_element(By.ID, "nextStep").click()
    self.driver.find_element(By.CSS_SELECTOR, ".right-icon .el-input__inner").send_keys("Apd1234567!")
    self.driver.find_element(By.CSS_SELECTOR, ".el-checkbox__inner").click()
    self.driver.find_element(By.ID, "nextStep").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(11) .el-input__inner").send_keys("1111")
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(12) .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(12) .el-input__inner").send_keys("1111")
    element = self.driver.find_element(By.CSS_SELECTOR, ".sign-up-btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "nextStep")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".sign-up-btn").click()
    self.driver.find_element(By.ID, "nextStep").click()
    self.driver.find_element(By.ID, "backToLoginSuccess").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(3) > .el-input__inner").click()
  